
users:
  cres:
    ids:
      - 52177891
      - 42294863
    nickname: Cres
    aliases:
      - c
  shou:
    ids:
      - 48273646
    nickname: Shou
    aliases:
      - s
    timezone: "Eastern Time (US & Canada)"
  group:
    ids:
      - 2998214
    nickname: Chat Group
    aliases:
      - g

telegram:
  token: '<your-token>'
  refresh_interval: 1
  logging_status: ~

fondbot:
  public: false
  authorized:
#    - shou
    - cres
  denial_message: 對不起qwq，主人不讓人家和陌生人搭話個說ww
  pagination:
    default_count: 10
